// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © abdullah2202

//@version=5

indicator(title="Support & Resistance", shorttitle="S 'n' R", overlay=true)

//NumberOfCandles = input.int(100, title="No. Previous Candles to look at")
NumberOfCandles = 50
Sensitivity = input.int(2, title="Sensitivity")

supports = array.new_float(0)
resistances = array.new_float(0)

support_1 = 0
support_2 = 0

support = 0
resistance = 0

// Iterate candles from 1 to inpNumberOfCandles and find S and R
for i=1 to NumberOfCandles
    if close[i] > open[i] and close[i+1] < open[i+1]
        array.push(supports, open[i])
    if close[i] < open[i] and close[i+1] > open[i+1]
        array.push(resistances, open[i])

// Draw Supports
//for i=0 to (array.size(supports) == 0 ? na : array.size(supports) - 1)
   // plot(supports[i] > 0 ? supports[i] : na)

// Draw Resistances
//if(array.size(resistances) > 0)
//    for i=0 to array.size(resistances) - 1
//        hline(price=resistances[i], color=color.red, linestyle=hline.style_solid, linewidth=2)

hline(supports[1], color=color.red, linestyle=hline.style_solid, linewidth=2)
plot(na)

// Send out an alert if this candle meets our conditions
//alertcondition(bearishSignal or bullishSignal, title="Engulfing Trade Alert!", message="Engulfing Signal for XXX")